import type { Metadata } from 'next'
import { Inter , Poppins } from 'next/font/google'

import './globals.css'
import CustomFont from 'next/font/local'

const cfont = CustomFont({
  src: '../../public/fonts/KrabbyPatty.ttf',
  variable: '--font-krabby',
})




const poppins = Poppins({ subsets: ['latin'] , weight: ['400'] , variable :'--font-Poppins'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${cfont.variable}`}>{children}</body>
    </html>
  )
}
