import type { Metadata } from 'next'
import { Inter , Poppins } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] , variable :'--font-Inter' })
const poppins = Poppins({ subsets: ['latin'] , weight: ['400'] , variable :'--font-Poppins'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable}`}>{children}</body>
    </html>
  )
}
